%% createRankingTable
function ranking = createRankingTable(metadata, distances)
    % Create ranking table (für Trajektorien ODER Segmente)
    % Automatische Erkennung: hat segment_id → Segment, sonst Trajektorie
    
    if ismember('segment_id', metadata.Properties.VariableNames)
        % ✅ SEGMENT
        ranking = table(...
            metadata.segment_id, ...
            metadata.bahn_id, ...
            distances, ...
            (1:length(distances))', ...
            metadata.length, ...
            metadata.duration, ...
            'VariableNames', {'segment_id', 'bahn_id', 'distance', 'rank', 'length', 'duration'});
    else
        % ✅ TRAJEKTORIE
        ranking = table(...
            metadata.bahn_id, ...
            distances, ...
            (1:length(distances))', ...
            metadata.length, ...
            metadata.duration, ...
            'VariableNames', {'bahn_id', 'distance', 'rank', 'length', 'duration'});
    end
    
    ranking = sortrows(ranking, 'distance', 'ascend');
    ranking.rank = (1:height(ranking))';
end