function segments = loadSegments(conn, schema, bahn_id, mode)
    % Load all segments for a trajectory
    query_count = sprintf(...
        ['SELECT COUNT(*) as num_segments ' ...
         'FROM robotervermessung.%s.bahn_metadata ' ...
         'WHERE bahn_id = ''%s'' AND segment_id != bahn_id'], ...  % <-- GEÄNDERT
        schema, bahn_id);
    
    result = fetch(conn, query_count);
    num_segments = result.num_segments;
    
    segments = cell(num_segments, 1);
    
    for i = 1:num_segments
        segment_id = sprintf('%s_%d', bahn_id, i);
        
        if strcmp(mode, 'position')
            query = sprintf(...
                ['SELECT x_soll, y_soll, z_soll ' ...
                 'FROM robotervermessung.%s.bahn_position_soll ' ...
                 'WHERE segment_id = ''%s'' ' ...
                 'ORDER BY timestamp'], ...
                schema, segment_id);
        else  % joint_states
            query = sprintf(...
                ['SELECT joint_1, joint_2, joint_3, joint_4, joint_5, joint_6 ' ...
                 'FROM robotervermessung.%s.bahn_joint_states ' ...
                 'WHERE segment_id = ''%s'' ' ...
                 'ORDER BY timestamp'], ...
                schema, segment_id);
        end
        
        result = fetch(conn, query);
        segments{i} = table2array(result);
    end
end